project:
  type: website

website:
  title: "Jail Deaths in U.S.A."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plots.qmd
        text: Plots
    right:
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



