---
title: "Cause of death"
author: "Sruthi"
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(gganimate)
```

```{r}
all_deaths <- readr::read_csv("all_deaths.csv")
all_jails <- readr::read_csv("all_jails.csv")
```

```{r}
all_deaths <- all_deaths|>
  filter(!is.na(id))
all_jails <- all_jails|>
  filter(!is.na(id))
```

```{r}
# Merge datasets
merged_data <- left_join(all_deaths, all_jails, by = "id")

# Mapping for causes
cause_mapping <- c(
  "AC" = "Accident",
  "A" = "Accident",   # Add mapping for "A" to "Accident"
  "S" = "Suicide",
  "H" = "Homicide",
  "M" = "Medical Issue",
  "O" = "Other",
  "DA" = "Drug/Alcohol related"
)

# Recode cause_short to cause_full using the mapping
merged_data <- merged_data %>%
  mutate(cause_full = ifelse(cause_short %in% c("AC", "A"), "Accident", recode(cause_short, !!!cause_mapping)))

# Create ggplot for visualization
static_plot <- merged_data %>%
  ggplot(aes(x = year, fill = cause_full)) +
  geom_bar() +
  scale_fill_manual(values = c("Accident" = "steelblue",   
                               "Suicide" = "aquamarine2",
                               "Homicide" = "pink3",
                               "Medical Issue" ="pink4",
                               "Other" = "pink1",
                               "Drug/Alcohol related" = "tomato")) +
  labs(title = "Distribution of Deaths by Cause (2008-2019)", subtitle = "Most deaths are because of sicknesses that go unaddressed behind bars.",
       x = "Year", y = "Count", fill = "Cause of Death") +
  theme_minimal() +
  theme(legend.position = "right", 
        title.text = element_text(face = "bold"))

  animated_plot <- static_plot +
  transition_states(cause_full, transition_length = 2, state_length = 1, wrap = TRUE)+
     scale_x_continuous(breaks = seq(2008, 2019, by = 1))


anim_save("cause.gif", animate(animated_plot))


```


