---
title: "Race vs. Number of Deaths 2"
format: html
author: Sruthi
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(gganimate)
```

```{r}
all_deaths <- readr::read_csv("all_deaths.csv")
all_jails <- readr::read_csv("all_jails.csv")
```

```{r}
all_deaths <- all_deaths|>
  filter(!is.na(id))
all_jails <- all_jails|>
  filter(!is.na(id))
```

```{r}
merged_data <- left_join(all_deaths, all_jails, by = "id")

race_mapping <- c(
  "A" = "Asian",
  "AI" = "American Indian",
  "B" = "Black",
  "H" = "Hispanic",
  "O" = "Other",
  "PI" = "Pacific Islander",
  "W" = "White",
  "NA" = "Unknown"
)


merged_data <- merged_data |>
  mutate(race_full = recode(race, !!!race_mapping))
```

```{r}
static_plot <- merged_data %>%
  filter(year >= 2008 & year <= 2019) %>%
  ggplot(aes(x = year, fill = race_full)) +
  geom_bar() +
  labs(title = "Number of Jail Deaths by Race (2008-2019)",
       x = "Year",
       y = "Number of Deaths",
       fill = "Race") +
  theme_minimal() 

animated_plot <- static_plot +
  transition_states(race, transition_length = 2, state_length = 1, wrap = TRUE)

animated_plot
```
